### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ruigehaoshuai** [lyq1996/an_supplicant#5]
有心跳包不，老版本可认证时间长会掉线

**Comment by lyq1996** [comment]
大约多长时间会掉线呢，这里面自带心跳，大约20s发送一次心跳包

**Comment by JoKerHuangBoy** [comment]
能否增加一个被人踢下线的通知，图形版暂时还没用，目前用的仍然是那个比较旧的交易版。

**Comment by lyq1996** [comment]
@JoKerHuangBoy 
你是说被强制断网的通知吗？
一般情况下并不需要吧,反正它也会自动重连。(除了夜间断网连不上去)

并且在你设置并不自动重连的话,它会退出,这样也就算通知吧,只是不知道具体被下线的原因。

如果要实现的话:
在上线之后开启一个线程, 持续监听本地udp的4999端口。
[协议在这里](https://github.com/lyq1996/swiftz-protocal#being-disconnected)
这样的话代码又要重构了..

**Comment by JoKerHuangBoy** [comment]
最新測試，舊版的Py版和新版都失效了，全部認證超時…來自城建的小學生
